# Generated by Django 3.2.3 on 2021-05-27 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mRegister',
            fields=[
                ('Registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('Aadhar', models.BigIntegerField(unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Names', models.CharField(max_length=20)),
                ('Phone', models.BigIntegerField(unique=True)),
                ('Dob', models.DateField(default=datetime.datetime(2021, 5, 27, 6, 6, 26, 855128, tzinfo=utc))),
                ('PinCode', models.IntegerField(max_length=6)),
                ('VSlot', models.CharField(max_length=20)),
                ('VDate', models.DateField(default=datetime.datetime(2021, 5, 27, 6, 6, 26, 855128, tzinfo=utc))),
            ],
        ),
    ]
